version: '3.7'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - app:/home/app/web
    links:
      - web:web
    networks:
      - webapp_net
    ports:
      - 80:80
    depends_on:
      - web
    restart: always

  web:
    build: ./app
    container_name: web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - app:/home/app/web
    networks:
      - webapp_net
    expose:
      - 8000
    restart: always

  redis:
    container_name: redis
    image: redis:6.0.5-alpine
    volumes:
      - redis_data:/data
    networks:
      - webapp_net
    ports:
      - 6379:6379
    restart: always

  postgres:
    build: ./postgres
    container_name: postgres
    volumes:
      - postgres_backups:/backup
      - postgres_data:/var/lib/postgresql
    networks:
      - webapp_net
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
       - pgadmin:/root/.pgadmin
    networks:
      - webapp_net
    ports:
      - 5050:80
    restart: always

networks:
  webapp_net:
    driver: bridge
    name: webapp_net

volumes:
  app:
  postgres_backups:
  postgres_data:
  pgadmin:
  redis_data:
