version: '3.7'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
    networks:
      - webapp_net
    ports:
      - 1337:80
    networks:
      - webapp_net
    depends_on:
      - web
    restart: always

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: web
    image: webapp:0.0.1
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
    networks:
      - webapp_net
    expose:
      - 8000
    env_file:
      - ./.env.web.prod
    restart: always

  db:
    build: ./postgres
    container_name: db
    volumes:
      - ./postgres/pgdata:/data
    networks:
      - webapp_net
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
       - ./pgadmin:/root/.pgadmin
    networks:
      - webapp_net
    ports:
      - 5050:80
    env_file:
      - ./.env.db
    restart: always

networks:
  webapp_net:
    driver: bridge
    name: webapp_net
