# Generated by Django 3.0.7 on 2020-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Информация')),
                ('image', models.ImageField(upload_to='guides/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Гид и менеджер',
                'verbose_name_plural': 'Гиды и менеджеры',
            },
        ),
    ]
