# Generated by Django 3.0.7 on 2020-06-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chogori', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(upload_to='guides/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
